engine: tesseract
langs: [vie]
dpi: 300

preprocess_steps: [orientation, deskew, denoise]

layout: tesseract
table: cv
qa_threshold: 0.75

input_dir: ./dataset/lpbank
output_dir: ./output
review_dir: ./review
artifacts_dir: ./artifacts

ground_truth_dir: ./ground_truth/lpbank # directory containing ground truth text files for evaluation
