engine: chandra
langs: [vie, eng]

preprocess_steps: [grayscale, deskew, binarize]

input_dir: ./dataset
output_dir: ./output/low_quality_handwritten

ground_truth_dir: ./ground_truth/handwritten # directory containing ground truth text files for evaluation
